<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://TargetNamespace.com/FlightService_retrieveFlightDetails_response"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns0="com.flyinghigh/operations/flightservice"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="com.flyinghigh/operations/common" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../XMLSchema_417271354.xsd"/>
        <oracle-xsl-mapper:rootElement name="getFlightDetailsResponse"
                                       namespace="com.flyinghigh/operations/flightservice"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_flightDetails.xsd"/>
        <oracle-xsl-mapper:rootElement name="Flights"
                                       namespace="http://TargetNamespace.com/FlightService_retrieveFlightDetails_response"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED FEB 25 20:25:20 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Flights>
      <tns:FlightCode>
        <tns:CarrierCode>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:FlightCode/com:CarrierCode"/>
        </tns:CarrierCode>
        <tns:FlightNumber>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:FlightCode/com:FlightNumber"/>
        </tns:FlightNumber>
      </tns:FlightCode>
      <tns:FlightStatus>
        <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:FlightStatus"/>
      </tns:FlightStatus>
      <tns:FlightDate>
        <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:FlightDate"/>
      </tns:FlightDate>
      <tns:Departure>
        <tns:Time>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:DepartureTime"/>
        </tns:Time>
        <tns:AirportCode>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Origin/com:IATACode"/>
        </tns:AirportCode>
        <tns:AirportName>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Origin/com:Name"/>
        </tns:AirportName>
        <tns:City>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Origin/com:City"/>
        </tns:City>
        <tns:Country>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Origin/com:Country"/>
        </tns:Country>
      </tns:Departure>
      <tns:Destination>
        <tns:Time>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:ArrivalTime"/>
        </tns:Time>
        <tns:AirportCode>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Destination/com:IATACode"/>
        </tns:AirportCode>
        <tns:AirportName>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Destination/com:Name"/>
        </tns:AirportName>
        <tns:City>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Destination/com:City"/>
        </tns:City>
        <tns:Country>
          <xsl:value-of select="/ns0:getFlightDetailsResponse/ns0:Destination/com:Country"/>
        </tns:Country>
      </tns:Destination>
    </tns:Flights>
  </xsl:template>
</xsl:stylesheet>
