<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CustomerService"
     targetNamespace="com.flyinghigh/operations/customerservice"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:cus="com.flyinghigh/operations/customerservice"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CustomerComplaintHandler">
        <plnk:role name="CustomerService_ptt" portType="cus:CustomerService_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="com.flyinghigh/operations/customerservice" location="CustomerService.wsdl"/>
</wsdl:definitions>
