<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CustomerComplaintProcess"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/CustomerComplaintProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CustomerComplaintProcess.CustomerComplaintProcess.service">
        <plnk:role name="CustomerComplaintProcessPortTypeCallBack" portType="tns:CustomerComplaintProcessPortTypeCallBack"/>
        <plnk:role name="CustomerComplaintProcessPortType" portType="tns:CustomerComplaintProcessPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CustomerComplaintProcess" location="CustomerComplaintProcess.wsdl"/>
</wsdl:definitions>
