<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrieveFlightDetails"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="com.flyinghigh/operations/flightservice"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/FlyingHighAirlineServices/FlightService/retrieveFlightDetails"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="com.flyinghigh/operations/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/retrieveFlightDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrieveFlightDetails"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FlightService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="getFlightDetailsResponse"
                                       namespace="com.flyinghigh/operations/flightservice"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN FEB 22 19:18:42 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getFlightDetailsResponse>
      <tns:FlightCode>
        <ns2:CarrierCode>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:AIRLINE_CODE"/>
        </ns2:CarrierCode>
        <ns2:FlightNumber>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:FLIGHT_NUMBER"/>
        </ns2:FlightNumber>
      </tns:FlightCode>
      <tns:FlightDate>
        <xsl:value-of select="concat(xp20:format-dateTime (/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_TIME, '[Y0001]-[M01]-[D01]T' ),/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_TIMEZONE)"/>
      </tns:FlightDate>
      <tns:FlightStatus>
        <xsl:value-of select="dvm:lookupValue ('../DVM/FlightStatusMap', 'FlightStatusShortDB', /ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:FLIGHT_STATUS, 'FlightStatus', 'CouldNotBeFound' )"/>
      </tns:FlightStatus>
      <tns:Origin>
        <ns2:IATACode></ns2:IATACode>
        <ns2:Name>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_AIRPORT"/>
        </ns2:Name>
        <ns2:Country>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_COUNTRY"/>
        </ns2:Country>
        <ns2:City>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_CITY"/>
        </ns2:City>
      </tns:Origin>
      <tns:Destination>
        <ns2:Name>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DESTINATION_AIRPORT"/>
        </ns2:Name>
        <ns2:Country>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DESTINATION_COUNTRY"/>
        </ns2:Country>
        <ns2:City>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DESTINATION_CITY"/>
        </ns2:City>
      </tns:Destination>
      <tns:DepartureTime>
        <xsl:value-of select="concat(xp20:format-dateTime (/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_TIME, '[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' ),/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:DEPARTURE_TIMEZONE)"/>
      </tns:DepartureTime>
      <tns:ArrivalTime>
        <xsl:value-of select="concat(xp20:format-dateTime (/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:ARRIVAL_TIME, '[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' ),/ns0:OutputParameters/ns0:RETRIEVE_FLIGHT_DETAILS/ns0:ARRIVAL_TIMEZONE)"/>
      </tns:ArrivalTime>
    </tns:getFlightDetailsResponse>
  </xsl:template>
</xsl:stylesheet>
