<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrievePassengerList"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="com.flyinghigh/operations/flightservice"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/FlyingHighAirlineServices/FlightService/retrievePassengerList"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="com.flyinghigh/operations/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/retrievePassengerList.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrievePassengerList"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FlightService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="retrievePassengerListForFlightResponse"
                                       namespace="com.flyinghigh/operations/flightservice"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN FEB 22 17:29:52 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:retrievePassengerListForFlightResponse>
      <tns:FlightCode>
        <ns2:CarrierCode>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_PASSENGER_LIST/ns0:AIRLINE_CODE"/>
        </ns2:CarrierCode>
        <ns2:FlightNumber>
          <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_PASSENGER_LIST/ns0:FLIGHT_NUMBER"/>
        </ns2:FlightNumber>
      </tns:FlightCode>
      <tns:FlightDate>
        <xsl:value-of select="/ns0:OutputParameters/ns0:RETRIEVE_PASSENGER_LIST/ns0:DEPARTURE_TIME"/>
      </tns:FlightDate>
      <tns:PassengerList>
        <ns2:TotalNumberOfPassengers>
          <xsl:value-of select="count (/ns0:OutputParameters/ns0:RETRIEVE_PASSENGER_LIST/ns0:PASSENGERS/ns0:PASSENGERS_ITEM )"/>
        </ns2:TotalNumberOfPassengers>
        <ns2:Passengers>
          <xsl:for-each select="/ns0:OutputParameters/ns0:RETRIEVE_PASSENGER_LIST/ns0:PASSENGERS/ns0:PASSENGERS_ITEM">
            <xsl:if test=".">
              <ns2:Passenger>
                <ns2:FirstName>
                  <xsl:value-of select="ns0:FIRST_NAME"/>
                </ns2:FirstName>
                <ns2:LastName>
                  <xsl:value-of select="ns0:LAST_NAME"/>
                </ns2:LastName>
                <xsl:if test="ns0:COUNTRY_CODE">
                  <ns2:Country>
                    <xsl:value-of select="ns0:COUNTRY_CODE"/>
                  </ns2:Country>
                </xsl:if>
                <ns2:FrequentFlyerNumber>
                  <xsl:value-of select="ns0:FREQUENT_FLYER_NUMBER"/>
                </ns2:FrequentFlyerNumber>
                <xsl:if test="ns0:SEAT">
                  <ns2:Seat>
                    <xsl:value-of select="ns0:SEAT"/>
                  </ns2:Seat>
                </xsl:if>
              </ns2:Passenger>
            </xsl:if>
          </xsl:for-each>
        </ns2:Passengers>
      </tns:PassengerList>
    </tns:retrievePassengerListForFlightResponse>
  </xsl:template>
</xsl:stylesheet>
