<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/setFlightStatus"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="com.flyinghigh/operations/flightservice"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="com.flyinghigh/operations/common" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/FlyingHighAirlineServices/FlightService/setFlightStatus">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FlightService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="sendFlightStatusUpdateRequest"
                                       namespace="com.flyinghigh/operations/flightservice"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/setFlightStatus.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/setFlightStatus"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN FEB 22 17:51:05 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_FLIGHT_NUMBER>
        <xsl:value-of select="/ns0:sendFlightStatusUpdateRequest/ns0:FlightCode/ns1:FlightNumber"/>
      </tns:P_FLIGHT_NUMBER>
      <tns:P_AIRLINE_CODE>
        <xsl:value-of select="/ns0:sendFlightStatusUpdateRequest/ns0:FlightCode/ns1:CarrierCode"/>
      </tns:P_AIRLINE_CODE>
      <tns:P_DEPARTURE_DATE>
        <xsl:value-of select="/ns0:sendFlightStatusUpdateRequest/ns0:FlightDate"/>
      </tns:P_DEPARTURE_DATE>
      <tns:P_FLIGHT_STATUS>
        <xsl:value-of select="dvm:lookupValue ('../DVM/FlightStatusMap', 'FlightStatus', /ns0:sendFlightStatusUpdateRequest/ns0:FlightStatus, 'FlightStatusShortDB', 'XXX' )"/>
      </tns:P_FLIGHT_STATUS>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
